name: integration_tests

on: [push, pull_request]

jobs:
  integration_tests:
    runs-on: ubuntu-20.04 # linux required if you want to use docker
    steps:
    - name: Remove android, dotnet and other bull$#!@
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build docker images
      run: docker build -t mbari_lrauv . -f docker/tests/Dockerfile
    - name: Run tests
      run: docker run mbari_lrauv
